# Generated by Django 5.1.9 on 2025-11-19 00:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255, verbose_name='service name')),
                ('credential_type', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email_smtp', 'Email SMTP'), ('email_brevo', 'Email Brevo'), ('other', 'Other')], max_length=50, verbose_name='credential type')),
                ('api_key', models.CharField(blank=True, max_length=500, verbose_name='api key')),
                ('api_secret', models.CharField(blank=True, max_length=500, verbose_name='api secret')),
                ('access_token', models.CharField(blank=True, max_length=500, verbose_name='access token')),
                ('refresh_token', models.CharField(blank=True, max_length=500, verbose_name='refresh token')),
                ('webhook_url', models.URLField(blank=True, verbose_name='webhook url')),
                ('phone_number_id', models.CharField(blank=True, max_length=255, verbose_name='phone number id')),
                ('business_account_id', models.CharField(blank=True, max_length=255, verbose_name='business account id')),
                ('additional_config', models.JSONField(blank=True, default=dict, verbose_name='additional config')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='expires at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'api credential',
                'verbose_name_plural': 'api credentials',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('color', models.CharField(blank=True, max_length=7, verbose_name='color')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='phone')),
                ('whatsapp_number', models.CharField(blank=True, max_length=20, verbose_name='whatsapp number')),
                ('position', models.CharField(blank=True, max_length=255, verbose_name='position')),
                ('department', models.CharField(blank=True, max_length=255, verbose_name='department')),
                ('is_primary', models.BooleanField(default=False, verbose_name='is primary')),
                ('is_decision_maker', models.BooleanField(default=False, verbose_name='is decision maker')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'contact',
                'verbose_name_plural': 'contacts',
                'ordering': ['-is_primary', 'first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='LeadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('color', models.CharField(blank=True, max_length=7, verbose_name='color')),
                ('order_position', models.IntegerField(default=0, verbose_name='order position')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'lead status',
                'verbose_name_plural': 'lead statuses',
                'ordering': ['order_position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('color', models.CharField(blank=True, max_length=7, verbose_name='color')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('subject', models.CharField(max_length=255, verbose_name='subject')),
                ('body', models.TextField(verbose_name='body')),
                ('template_type', models.CharField(choices=[('welcome', 'Welcome'), ('follow_up', 'Follow Up'), ('reminder', 'Reminder'), ('custom', 'Custom')], max_length=50, verbose_name='template type')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_templates', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'verbose_name': 'email template',
                'verbose_name_plural': 'email templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='company name')),
                ('industry', models.CharField(blank=True, max_length=255, verbose_name='industry')),
                ('website', models.URLField(blank=True, verbose_name='website')),
                ('is_client', models.BooleanField(default=False, verbose_name='is client')),
                ('lead_source', models.CharField(blank=True, max_length=255, verbose_name='lead source')),
                ('lead_score', models.IntegerField(default=0, verbose_name='lead score')),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='estimated value')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('last_contact_date', models.DateTimeField(blank=True, null=True, verbose_name='last contact date')),
                ('next_follow_up', models.DateTimeField(blank=True, null=True, verbose_name='next follow up')),
                ('converted_to_client_at', models.DateTimeField(blank=True, null=True, verbose_name='converted to client at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL, verbose_name='assigned to')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='leads.category', verbose_name='category')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='leads.leadstatus', verbose_name='status')),
            ],
            options={
                'verbose_name': 'lead',
                'verbose_name_plural': 'leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email'), ('sms', 'SMS'), ('other', 'Other')], max_length=50, verbose_name='channel')),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='subject')),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('pending', 'Pending'), ('resolved', 'Resolved')], default='open', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_conversations', to=settings.AUTH_USER_MODEL, verbose_name='assigned to')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='leads.contact', verbose_name='contact')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='leads.lead', verbose_name='lead')),
            ],
            options={
                'verbose_name': 'conversation',
                'verbose_name_plural': 'conversations',
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='contact',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='leads.lead', verbose_name='lead'),
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('call', 'Call'), ('email', 'Email'), ('meeting', 'Meeting'), ('note', 'Note'), ('task', 'Task'), ('message', 'Message'), ('status_change', 'Status Change'), ('other', 'Other')], max_length=50, verbose_name='activity type')),
                ('description', models.TextField(verbose_name='description')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='leads.contact', verbose_name='contact')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='leads.lead', verbose_name='lead')),
            ],
            options={
                'verbose_name': 'activity',
                'verbose_name_plural': 'activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('user', 'User'), ('contact', 'Contact'), ('system', 'System')], max_length=20, verbose_name='sender type')),
                ('sender_id', models.CharField(max_length=255, verbose_name='sender id')),
                ('content', models.TextField(verbose_name='content')),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('file', 'File'), ('audio', 'Audio'), ('video', 'Video')], default='text', max_length=20, verbose_name='message type')),
                ('external_message_id', models.CharField(blank=True, max_length=255, verbose_name='external message id')),
                ('is_read', models.BooleanField(default=False, verbose_name='is read')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='sent at')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='delivered at')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='read at')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='leads.conversation', verbose_name='conversation')),
            ],
            options={
                'verbose_name': 'message',
                'verbose_name_plural': 'messages',
                'ordering': ['sent_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('filter_config', models.JSONField(default=dict, verbose_name='filter config')),
                ('is_public', models.BooleanField(default=False, verbose_name='is public')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_filters', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'saved filter',
                'verbose_name_plural': 'saved filters',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_tags', to='leads.lead')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_tags', to='leads.tag')),
            ],
            options={
                'verbose_name': 'lead tag',
                'verbose_name_plural': 'lead tags',
                'unique_together': {('lead', 'tag')},
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='tags',
            field=models.ManyToManyField(related_name='leads', through='leads.LeadTag', to='leads.tag'),
        ),
        migrations.CreateModel(
            name='ContactTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_tags', to='leads.contact')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_tags', to='leads.tag')),
            ],
            options={
                'verbose_name': 'contact tag',
                'verbose_name_plural': 'contact tags',
                'unique_together': {('contact', 'tag')},
            },
        ),
        migrations.AddField(
            model_name='contact',
            name='tags',
            field=models.ManyToManyField(related_name='contacts', through='leads.ContactTag', to='leads.tag'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('task_type', models.CharField(choices=[('call', 'Call'), ('email', 'Email'), ('meeting', 'Meeting'), ('follow_up', 'Follow Up'), ('other', 'Other')], default='other', max_length=50, verbose_name='task type')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20, verbose_name='priority')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='status')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='due date')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='assigned to')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='leads.contact', verbose_name='contact')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='leads.lead', verbose_name='lead')),
            ],
            options={
                'verbose_name': 'task',
                'verbose_name_plural': 'tasks',
                'ordering': ['-due_date', '-created_at'],
            },
        ),
    ]
