# Generated by Django 5.1.9 on 2025-12-03 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_campaign_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='is read'),
        ),
    ]
